# 1: 
#   linear:
#     x:
#     y:
#     z:
#   angular:
#     x:
#     y:
#     z:

twist_pub:
  ros__parameters:
    commands:
      1: 
        linear:
          x: 0.1
          y: 0
          z: 0
        angular:
          x: 0
          y: 0
          z: 0